specialties_dict = {
    "ACA": "Acupuncturist",
    "MAI": "Allergy and Immunology",
    "MAA": "Anesthesiology",
    "DCH": "Chiropractic",
    "DEN": "Dentistry",
    "MDE": "Dermatology",
    "MEM": "Emergency Medicine",
    "MFP": "Family Practice",
    "MPM": "General Preventive Medicine",
    "MHH": "Hand",
    "MMM": "Internal Medicine",
    "MMV": "Internal Medicine - Cardiovascular Disease",
    "MME": "Internal Medicine - Endocrinology, Diabetes and Metabolism",
    "MMG": "Internal Medicine - Gastroenterology",
    "MMH": "Internal Medicine - Hematology",
    "MMI": "Internal Medicine - Infectious Disease",
    "MMN": "Internal Medicine - Nephrology",
    "MMP": "Internal Medicine - Pulmonary Disease",
    "MMR": "Internal Medicine - Rheumatology",
    "MOQ": "Medicine Otherwise Qualified",
    "MNS": "Neurological Surgery",
    "MPN": "Neurology",
    "MOG": "Obstetrics and Gynecology",
    "MPO": "Occupational Medicine",
    "MMO": "Oncology - Internal Medicine",
    "MOP": "Ophthalmology",
    "OPT": "Optometry",
    "MOS": "Orthopaedic Surgery",
    "MTO": "Otolaryngology",
    "MPA": "Pain Medicine",
    "MHA": "Pathology",
    "MPR": "Physical Medicine & Rehabilitation",
    "MPS": "Plastic Surgery",
    "POD": "Podiatry",
    "MPD": "Psychiatry",
    "PSY": "Psychology",
    "MNB": "Spine",
    "MSY": "Surgery",
    "MSG": "Surgery - General Vascular",
    "MTS": "Thoracic Surgery",
    "MTT": "Toxicology",
    "MUU": "Urology"
}
